// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/ratelimit/ratelimit.proto

package ratelimit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RateLimitConfig defines the configuration for a rate limiter
type RateLimitConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Algorithm      string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`                                  // token_bucket, sliding_window, fixed_window, leaky_bucket
	Limit          int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                         // max requests/tokens
	WindowSeconds  int32                  `protobuf:"varint,3,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`    // time window in seconds
	RefillRate     int32                  `protobuf:"varint,4,opt,name=refill_rate,json=refillRate,proto3" json:"refill_rate,omitempty"`             // tokens per interval (for token bucket)
	RefillInterval int32                  `protobuf:"varint,5,opt,name=refill_interval,json=refillInterval,proto3" json:"refill_interval,omitempty"` // interval in seconds (for token bucket)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RateLimitConfig) Reset() {
	*x = RateLimitConfig{}
	mi := &file_proto_ratelimit_ratelimit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitConfig) ProtoMessage() {}

func (x *RateLimitConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimit_ratelimit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitConfig.ProtoReflect.Descriptor instead.
func (*RateLimitConfig) Descriptor() ([]byte, []int) {
	return file_proto_ratelimit_ratelimit_proto_rawDescGZIP(), []int{0}
}

func (x *RateLimitConfig) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *RateLimitConfig) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RateLimitConfig) GetWindowSeconds() int32 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

func (x *RateLimitConfig) GetRefillRate() int32 {
	if x != nil {
		return x.RefillRate
	}
	return 0
}

func (x *RateLimitConfig) GetRefillInterval() int32 {
	if x != nil {
		return x.RefillInterval
	}
	return 0
}

// SetRequest is the request message for configuring a rate limit
type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Config        *RateLimitConfig       `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_proto_ratelimit_ratelimit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimit_ratelimit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_proto_ratelimit_ratelimit_proto_rawDescGZIP(), []int{1}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetConfig() *RateLimitConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// SetResponse is the response message after configuring a rate limit
type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_proto_ratelimit_ratelimit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimit_ratelimit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_proto_ratelimit_ratelimit_proto_rawDescGZIP(), []int{2}
}

func (x *SetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// CheckRequest is the request message for checking if a request is allowed
type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_proto_ratelimit_ratelimit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimit_ratelimit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_ratelimit_ratelimit_proto_rawDescGZIP(), []int{3}
}

func (x *CheckRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CheckRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

// CheckResponse is the response message for a rate limit check
type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Remaining     int64                  `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`                     // remaining requests/tokens
	ResetAt       int64                  `protobuf:"varint,3,opt,name=reset_at,json=resetAt,proto3" json:"reset_at,omitempty"`          // Unix timestamp
	RetryAfter    int32                  `protobuf:"varint,4,opt,name=retry_after,json=retryAfter,proto3" json:"retry_after,omitempty"` // seconds until retry is allowed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_proto_ratelimit_ratelimit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimit_ratelimit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_ratelimit_ratelimit_proto_rawDescGZIP(), []int{4}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetRemaining() int64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *CheckResponse) GetResetAt() int64 {
	if x != nil {
		return x.ResetAt
	}
	return 0
}

func (x *CheckResponse) GetRetryAfter() int32 {
	if x != nil {
		return x.RetryAfter
	}
	return 0
}

// StatusRequest is the request message for getting rate limit status
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_ratelimit_ratelimit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimit_ratelimit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_ratelimit_ratelimit_proto_rawDescGZIP(), []int{5}
}

func (x *StatusRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// StatusResponse is the response message containing rate limit status
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Config        *RateLimitConfig       `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix timestamp
	NextReset     int64                  `protobuf:"varint,6,opt,name=next_reset,json=nextReset,proto3" json:"next_reset,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_ratelimit_ratelimit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimit_ratelimit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_ratelimit_ratelimit_proto_rawDescGZIP(), []int{6}
}

func (x *StatusResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StatusResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *StatusResponse) GetConfig() *RateLimitConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *StatusResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *StatusResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *StatusResponse) GetNextReset() int64 {
	if x != nil {
		return x.NextReset
	}
	return 0
}

// ResetRequest is the request message for resetting a rate limit
type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_proto_ratelimit_ratelimit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimit_ratelimit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_proto_ratelimit_ratelimit_proto_rawDescGZIP(), []int{7}
}

func (x *ResetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// ResetResponse is the response message after resetting a rate limit
type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_proto_ratelimit_ratelimit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimit_ratelimit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_proto_ratelimit_ratelimit_proto_rawDescGZIP(), []int{8}
}

func (x *ResetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResetResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_proto_ratelimit_ratelimit_proto protoreflect.FileDescriptor

const file_proto_ratelimit_ratelimit_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/ratelimit/ratelimit.proto\x12\vthrottle.v1\"\xb6\x01\n" +
	"\x0fRateLimitConfig\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12%\n" +
	"\x0ewindow_seconds\x18\x03 \x01(\x05R\rwindowSeconds\x12\x1f\n" +
	"\vrefill_rate\x18\x04 \x01(\x05R\n" +
	"refillRate\x12'\n" +
	"\x0frefill_interval\x18\x05 \x01(\x05R\x0erefillInterval\"T\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x06config\x18\x02 \x01(\v2\x1c.throttle.v1.RateLimitConfigR\x06config\"9\n" +
	"\vSetResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\">\n" +
	"\fCheckRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\"\x83\x01\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x03R\tremaining\x12\x19\n" +
	"\breset_at\x18\x03 \x01(\x03R\aresetAt\x12\x1f\n" +
	"\vretry_after\x18\x04 \x01(\x05R\n" +
	"retryAfter\"!\n" +
	"\rStatusRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\xd3\x01\n" +
	"\x0eStatusResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x124\n" +
	"\x06config\x18\x03 \x01(\v2\x1c.throttle.v1.RateLimitConfigR\x06config\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"next_reset\x18\x06 \x01(\x03R\tnextReset\" \n" +
	"\fResetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\";\n" +
	"\rResetResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key2\x88\x02\n" +
	"\tRateLimit\x128\n" +
	"\x03Set\x12\x17.throttle.v1.SetRequest\x1a\x18.throttle.v1.SetResponse\x12>\n" +
	"\x05Check\x12\x19.throttle.v1.CheckRequest\x1a\x1a.throttle.v1.CheckResponse\x12A\n" +
	"\x06Status\x12\x1a.throttle.v1.StatusRequest\x1a\x1b.throttle.v1.StatusResponse\x12>\n" +
	"\x05Reset\x12\x19.throttle.v1.ResetRequest\x1a\x1a.throttle.v1.ResetResponseB2Z0github.com/mohammadhprp/throttle/proto/ratelimitb\x06proto3"

var (
	file_proto_ratelimit_ratelimit_proto_rawDescOnce sync.Once
	file_proto_ratelimit_ratelimit_proto_rawDescData []byte
)

func file_proto_ratelimit_ratelimit_proto_rawDescGZIP() []byte {
	file_proto_ratelimit_ratelimit_proto_rawDescOnce.Do(func() {
		file_proto_ratelimit_ratelimit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ratelimit_ratelimit_proto_rawDesc), len(file_proto_ratelimit_ratelimit_proto_rawDesc)))
	})
	return file_proto_ratelimit_ratelimit_proto_rawDescData
}

var file_proto_ratelimit_ratelimit_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_ratelimit_ratelimit_proto_goTypes = []any{
	(*RateLimitConfig)(nil), // 0: throttle.v1.RateLimitConfig
	(*SetRequest)(nil),      // 1: throttle.v1.SetRequest
	(*SetResponse)(nil),     // 2: throttle.v1.SetResponse
	(*CheckRequest)(nil),    // 3: throttle.v1.CheckRequest
	(*CheckResponse)(nil),   // 4: throttle.v1.CheckResponse
	(*StatusRequest)(nil),   // 5: throttle.v1.StatusRequest
	(*StatusResponse)(nil),  // 6: throttle.v1.StatusResponse
	(*ResetRequest)(nil),    // 7: throttle.v1.ResetRequest
	(*ResetResponse)(nil),   // 8: throttle.v1.ResetResponse
}
var file_proto_ratelimit_ratelimit_proto_depIdxs = []int32{
	0, // 0: throttle.v1.SetRequest.config:type_name -> throttle.v1.RateLimitConfig
	0, // 1: throttle.v1.StatusResponse.config:type_name -> throttle.v1.RateLimitConfig
	1, // 2: throttle.v1.RateLimit.Set:input_type -> throttle.v1.SetRequest
	3, // 3: throttle.v1.RateLimit.Check:input_type -> throttle.v1.CheckRequest
	5, // 4: throttle.v1.RateLimit.Status:input_type -> throttle.v1.StatusRequest
	7, // 5: throttle.v1.RateLimit.Reset:input_type -> throttle.v1.ResetRequest
	2, // 6: throttle.v1.RateLimit.Set:output_type -> throttle.v1.SetResponse
	4, // 7: throttle.v1.RateLimit.Check:output_type -> throttle.v1.CheckResponse
	6, // 8: throttle.v1.RateLimit.Status:output_type -> throttle.v1.StatusResponse
	8, // 9: throttle.v1.RateLimit.Reset:output_type -> throttle.v1.ResetResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ratelimit_ratelimit_proto_init() }
func file_proto_ratelimit_ratelimit_proto_init() {
	if File_proto_ratelimit_ratelimit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ratelimit_ratelimit_proto_rawDesc), len(file_proto_ratelimit_ratelimit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ratelimit_ratelimit_proto_goTypes,
		DependencyIndexes: file_proto_ratelimit_ratelimit_proto_depIdxs,
		MessageInfos:      file_proto_ratelimit_ratelimit_proto_msgTypes,
	}.Build()
	File_proto_ratelimit_ratelimit_proto = out.File
	file_proto_ratelimit_ratelimit_proto_goTypes = nil
	file_proto_ratelimit_ratelimit_proto_depIdxs = nil
}
